version: '3.8'

networks:
  pca-net:
    driver: bridge

services:
  pca-app:
    image: konstp0/pca-app:latest
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
        - redis
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    networks:
      - pca-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - pca-net